### ISSUE TITLE
make orders php7 compatible

### ISSUE THREAD

**Issue by cbleek** [yawik/Orders#11]
https://php7.yawik.org/de/admin throws the following error (if loggedin as admin)

`[2018-10-15 10-41-20] Compile Error: Declaration of Orders\Repository\Orders::create(array $data = Array, $counterName = NULL, $counterFormat = NULL) must be compatible with Core\Repository\AbstractRepository::create(?array $data = NULL, $persist = false) in /var/www/YAWIK/module/Orders/src/Repository/Orders.php:0  @  https://php7.yawik.org/de/admin  @@  exception--2018-10-15--08-48--55d470d055.html`

Compile Error

Declaration of Orders\Repository\Orders::create(array $data = Array, $counterName = NULL, $counterFormat = NULL) must be compatible with Core\Repository\
AbstractRepository::create(?array $data = NULL, $persist = false) search?

```
Source file

File: .../www/YAWIK/module/Orders/src/Repository/Orders.php

 1:    <?php
 2:    /**
 3:     * YAWIK
 4:     *
 5:     * @filesource
 6:     * @license MIT
 7:     * @copyright  2013 - 2016 Cross Solution <http://cross-solution.de>
 8:     */
 9:
10:    /** */
11:    namespace Orders\Repository;
12:
13:    use Core\Repository\AbstractRepository;
14:    use Orders\Entity\OrderInterface;
15:    use Orders\Entity\OrderNumberCounter;

```

**Comment by cbleek** [comment]
@kilip we've forgotten to make the orders module php7 ready. Code works on php5.6 but not on php7.2

Can you take a look?

**Comment by kilip** [comment]
Yes, I can work on this issue

**Comment by kilip** [comment]
@cbleek my pull request build still failed, looks like we need to fix travis build. I will make a pull request again after the build is fixed.

**Comment by kilip** [comment]
Travis build fixed, module compatible with php 7 now
