### ISSUE TITLE
Make the fomular configurable

### ISSUE THREAD

**Issue by cbleek** [yawik/Orders#5]
@TiSiE please describe the task and assign it to kilip

**Comment by TiSiE** [comment]
The InvoiceAddress form should be customizable. Which means, fields' options should be configurable through a simple config file in the config/autoload directory.

Fortunately, most of the work is already done in [YAWIK](https://github.com/cross-solution/YAWIK)

* [Core/Form/CustomizableFieldsetInterface.php](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Core/src/Core/Form/CustomizableFieldsetInterface.php)
  Any Fieldset (or Form, as it's derived) implementing this interface can be customized, if an 
* [Core/Options/FieldsetCustomizationOptions.php](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Core/src/Core/Options/FieldsetCustomizationOptions.php) object is passed to it, which can be easily done with using a factory which extends from
* [Core/src/Core/Factory/Form/AbstractCustomizableFieldsetFactory.php](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Core/src/Core/Factory/Form/AbstractCustomizableFieldsetFactory.php)
* [Core/Form/CustomizableFieldsetTrait.php](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Core/src/Core/Form/CustomizableFieldsetTrait.php) can be used to implement the Interface painlessly.

This is currently done with [Jobs/src/Jobs/Form/JobboardSearch.php](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Jobs/src/Jobs/Form/JobboardSearch.php) and its [factory](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Jobs/src/Jobs/Factory/Form/JobboardSearchFactory.php), [options](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Jobs/src/Jobs/Options/JobboardSearchOptions.php) and [config file](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Jobs/config/JobboardSearchOptions.config.local.php.dist)

**Comment by cbleek** [comment]
Works. Thanks a lot
